import "./globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import NextSessionProvider from "./provider/NextSessionProvider";
import { Toaster } from "@/components/ui/toaster";

const lato = Lato({ weight: ["100", "400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <NextSessionProvider>{children}</NextSessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
